#!/bin/bash

echo "🚀 FlightWatch AI - Quick Testing Guide"
echo "========================================"
echo ""
echo "1️⃣  Start the Server:"
echo "   cd backend && npm run dev"
echo ""
echo "2️⃣  In another terminal, test signup:"
echo "   curl -X POST http://localhost:3000/api/auth/signup \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"name\":\"Test User\",\"email\":\"test@example.com\",\"password\":\"test123\"}'"
echo ""
echo "3️⃣  Create a watchlist (use token from response):"
echo "   curl -X POST http://localhost:3000/api/watchlists \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -H \"Authorization: Bearer YOUR_TOKEN\" \\"
echo "     -d '{\"sourceAirport\":\"NYC\",\"destinationAirport\":\"LAX\",\"departureDate\":\"2024-07-15\",\"budget\":500}'"
echo ""
echo "4️⃣  Check health:"
echo "   curl http://localhost:3000/health"
echo ""
echo "✅ All systems ready!"
